<a href="https://colab.research.google.com/github/ramrajv/NeuralNetworks/blob/main/Tensorflow_Upgrad_Optional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

## Question 1/2

### Libraries in TensorFlow
Consider the following Boolean matrix:

q = [[True, False], [True, False]]
Which of the following codes will produce a result like the one shown above? 

p = [[True, False],[False, False]]
Hint: You will need to explore the TensorFlow library to gain more understanding of the functions used in the following options

In [2]:
q = tf.Variable([[True, False], [True, False]])
r = tf.Variable([[True, True], [False, True]])
p=tf.math.logical_and(q,r)
print(p)

tf.Tensor(
[[ True False]
 [False False]], shape=(2, 2), dtype=bool)


## Question 2/2

### Reshaping Tensors
Use TensorFlow to complete this task. 

Task: Convert the tensor 'p' given in the cell below into a cube tensor of rank 3.

p = tf.Variable(np.random.randn(1,64))
(Note: More than one option can be correct.)

In [3]:
p = tf.Variable(np.random.randn(1,64))
reshaped_p = tf.reshape(p, (8,8,1))
print(reshaped_p)

tf.Tensor(
[[[ 0.42123401]
  [ 0.74342721]
  [-0.229582  ]
  [-2.12240776]
  [-0.3406986 ]
  [ 1.01825564]
  [ 1.11145046]
  [-0.18419785]]

 [[ 0.74670832]
  [ 1.23538167]
  [-0.00931121]
  [-0.24677722]
  [ 1.00860754]
  [-0.33800604]
  [-1.33739354]
  [-0.7236611 ]]

 [[ 0.01901151]
  [ 0.20952925]
  [-0.18226726]
  [-0.53651702]
  [-0.2283657 ]
  [-0.49532884]
  [-0.69983769]
  [-1.71084424]]

 [[ 0.77162496]
  [ 2.19420639]
  [-0.34649937]
  [ 0.7263704 ]
  [-1.83948425]
  [-0.09850177]
  [ 0.34828352]
  [-0.65399089]]

 [[ 0.52840724]
  [ 0.00345103]
  [ 0.32861572]
  [-0.36543828]
  [ 0.37818797]
  [-0.14312559]
  [ 0.14725214]
  [-0.94962549]]

 [[-0.28724339]
  [-1.00436632]
  [-1.22528238]
  [ 0.50461623]
  [ 0.35568659]
  [-0.04398989]
  [ 0.98649736]
  [ 1.76040452]]

 [[ 0.79289378]
  [-1.18224578]
  [-0.38331495]
  [ 1.81137505]
  [ 0.61391474]
  [ 1.5442144 ]
  [ 0.76819371]
  [-0.83858645]]

 [[ 0.11205751]
  [ 0.47338339]
  [-0.47080554]
  [-0.70509664]
  [ 1.73709265]

In [4]:
reshaped_p = tf.reshape(p, (4,4,4))
print(reshaped_p)

tf.Tensor(
[[[ 0.42123401  0.74342721 -0.229582   -2.12240776]
  [-0.3406986   1.01825564  1.11145046 -0.18419785]
  [ 0.74670832  1.23538167 -0.00931121 -0.24677722]
  [ 1.00860754 -0.33800604 -1.33739354 -0.7236611 ]]

 [[ 0.01901151  0.20952925 -0.18226726 -0.53651702]
  [-0.2283657  -0.49532884 -0.69983769 -1.71084424]
  [ 0.77162496  2.19420639 -0.34649937  0.7263704 ]
  [-1.83948425 -0.09850177  0.34828352 -0.65399089]]

 [[ 0.52840724  0.00345103  0.32861572 -0.36543828]
  [ 0.37818797 -0.14312559  0.14725214 -0.94962549]
  [-0.28724339 -1.00436632 -1.22528238  0.50461623]
  [ 0.35568659 -0.04398989  0.98649736  1.76040452]]

 [[ 0.79289378 -1.18224578 -0.38331495  1.81137505]
  [ 0.61391474  1.5442144   0.76819371 -0.83858645]
  [ 0.11205751  0.47338339 -0.47080554 -0.70509664]
  [ 1.73709265 -0.47225368 -0.45448402  3.12645302]]], shape=(4, 4, 4), dtype=float64)


In [5]:
reshaped_p = tf.reshape(p, (1,1,64))
print(reshaped_p)

tf.Tensor(
[[[ 0.42123401  0.74342721 -0.229582   -2.12240776 -0.3406986
    1.01825564  1.11145046 -0.18419785  0.74670832  1.23538167
   -0.00931121 -0.24677722  1.00860754 -0.33800604 -1.33739354
   -0.7236611   0.01901151  0.20952925 -0.18226726 -0.53651702
   -0.2283657  -0.49532884 -0.69983769 -1.71084424  0.77162496
    2.19420639 -0.34649937  0.7263704  -1.83948425 -0.09850177
    0.34828352 -0.65399089  0.52840724  0.00345103  0.32861572
   -0.36543828  0.37818797 -0.14312559  0.14725214 -0.94962549
   -0.28724339 -1.00436632 -1.22528238  0.50461623  0.35568659
   -0.04398989  0.98649736  1.76040452  0.79289378 -1.18224578
   -0.38331495  1.81137505  0.61391474  1.5442144   0.76819371
   -0.83858645  0.11205751  0.47338339 -0.47080554 -0.70509664
    1.73709265 -0.47225368 -0.45448402  3.12645302]]], shape=(1, 1, 64), dtype=float64)


## Question 1/2
### Gradient in TensorFlow
What is the slope of the curve 
$y = 3x^{3}+5x^{2}−3x+10 $ at 
$x=−2? $

In [7]:
# initiate the variable x
x = tf.Variable(-2.0)

# Using tf.gradientslope(), perform computation and return them to tape.
with tf.GradientTape() as tape:
    y = 3*x**3 + 5*x**2 - 3*x + 10 # Formula as per the equation above.

dy_dx = tape.gradient(y,x)
print(dy_dx.numpy())

13.0


### Upgrad answer

In [8]:
x = tf.Variable([-2], dtype=float)

with tf.GradientTape() as tape:
 y = 3*tf.pow(x,3) + 5*tf.pow(x,2) - 3*x +10

dy_dx = tape.gradient(y,x)

print(dy_dx.numpy()[0])

13.0


## Question 2/2
### Gradient in TensorFlow
Consider the function given below: -

$y = 3^{0.2x} + 5x^{2} - log(x) + tanh(x)$

Using TensorFlow, at $x = 10$, find out whether the function is increasing or decreasing.

### Approach

For a function to increase or decrease, the slope at the point should be positive or negative respectively. So, the derivative should give slope.

In [13]:
# Initiate the variable x
x = tf.Variable([10.0,11.0], dtype = float)

with tf.GradientTape() as tape:
    y = 3**(0.2*x) + 5 * tf.pow(x,2) - tf.math.log(x) + tf.math.tanh(x)

dy_dx = tape.gradient(y,x)

print(dy_dx.numpy())

[101.8775  112.37253]


### Upgrad solution

Feedback:
A function is said to be increasing at a given point if its slope at that point is positive. Find the slope of the curve at x = 10 and check its sign. If the sign is positive, then the function is increasing. If it is negative, then the function is decreasing. Use this code to find the slope of the function at x = 10.

In [14]:
x = tf.Variable((10), dtype=tf.float32)
with tf.GradientTape() as tape:
  y = tf.pow(3, 0.2 * x) + 5* tf.pow(x,2) - tf.math.log(x) + tf.math.tanh (x)
dy_dx = tape.gradient(y,x)
print("The slope of the function at x = 10 is ", dy_dx.numpy())

The slope of the function at x = 10 is  101.8775
