<a href="https://colab.research.google.com/github/ramrajv/NeuralNetworks/blob/main/Tensorflow_Upgrad_Optional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
import numpy as np

## Question 1/2

### Libraries in TensorFlow
Consider the following Boolean matrix:

q = [[True, False], [True, False]]
Which of the following codes will produce a result like the one shown above? 

p = [[True, False],[False, False]]
Hint: You will need to explore the TensorFlow library to gain more understanding of the functions used in the following options

In [2]:
q = tf.Variable([[True, False], [True, False]])
r = tf.Variable([[True, True], [False, True]])
p=tf.math.logical_and(q,r)
print(p)

tf.Tensor(
[[ True False]
 [False False]], shape=(2, 2), dtype=bool)


## Question 2/2

### Reshaping Tensors
Use TensorFlow to complete this task. 

Task: Convert the tensor 'p' given in the cell below into a cube tensor of rank 3.

p = tf.Variable(np.random.randn(1,64))
(Note: More than one option can be correct.)

In [5]:
p = tf.Variable(np.random.randn(1,64))
reshaped_p = tf.reshape(p, (8,8,1))
print(reshaped_p)

tf.Tensor(
[[[ 1.16221138]
  [ 0.80614682]
  [ 0.27504032]
  [-0.29658786]
  [ 1.08290885]
  [-1.09702616]
  [-0.59657741]
  [ 0.22968351]]

 [[-0.07610691]
  [ 0.45900602]
  [-0.86208158]
  [-0.31168607]
  [ 0.59027215]
  [-0.24033494]
  [ 1.48692071]
  [ 0.52293323]]

 [[ 0.56737852]
  [-0.80591461]
  [ 0.21702825]
  [-0.71104861]
  [ 0.58710716]
  [-1.27156263]
  [-1.19857883]
  [ 1.38847184]]

 [[-0.98953653]
  [-0.78299981]
  [ 2.18921726]
  [ 1.54421916]
  [ 1.5305066 ]
  [-1.28086073]
  [ 2.31988343]
  [-0.50405456]]

 [[-0.514213  ]
  [ 1.00762079]
  [ 0.30351509]
  [-1.06769039]
  [ 0.27000234]
  [-1.59531063]
  [-1.10439876]
  [ 0.275032  ]]

 [[-0.05950485]
  [-0.43121099]
  [-0.67757309]
  [-0.29537562]
  [-0.85793679]
  [-0.28913992]
  [-1.16336595]
  [ 0.31835729]]

 [[ 0.55263161]
  [-0.21645467]
  [-0.52667892]
  [ 1.14673374]
  [-0.00531444]
  [-0.30647242]
  [ 1.42481426]
  [-0.57809768]]

 [[ 0.34900209]
  [ 2.31437667]
  [-0.01108027]
  [ 0.21145963]
  [-0.91433977]

In [7]:
reshaped_p = tf.reshape(p, (4,4,4))
print(reshaped_p)

tf.Tensor(
[[[ 1.16221138  0.80614682  0.27504032 -0.29658786]
  [ 1.08290885 -1.09702616 -0.59657741  0.22968351]
  [-0.07610691  0.45900602 -0.86208158 -0.31168607]
  [ 0.59027215 -0.24033494  1.48692071  0.52293323]]

 [[ 0.56737852 -0.80591461  0.21702825 -0.71104861]
  [ 0.58710716 -1.27156263 -1.19857883  1.38847184]
  [-0.98953653 -0.78299981  2.18921726  1.54421916]
  [ 1.5305066  -1.28086073  2.31988343 -0.50405456]]

 [[-0.514213    1.00762079  0.30351509 -1.06769039]
  [ 0.27000234 -1.59531063 -1.10439876  0.275032  ]
  [-0.05950485 -0.43121099 -0.67757309 -0.29537562]
  [-0.85793679 -0.28913992 -1.16336595  0.31835729]]

 [[ 0.55263161 -0.21645467 -0.52667892  1.14673374]
  [-0.00531444 -0.30647242  1.42481426 -0.57809768]
  [ 0.34900209  2.31437667 -0.01108027  0.21145963]
  [-0.91433977 -0.53363234  0.62250672 -1.10617814]]], shape=(4, 4, 4), dtype=float64)


In [8]:
reshaped_p = tf.reshape(p, (1,1,64))
print(reshaped_p)

tf.Tensor(
[[[ 1.16221138  0.80614682  0.27504032 -0.29658786  1.08290885
   -1.09702616 -0.59657741  0.22968351 -0.07610691  0.45900602
   -0.86208158 -0.31168607  0.59027215 -0.24033494  1.48692071
    0.52293323  0.56737852 -0.80591461  0.21702825 -0.71104861
    0.58710716 -1.27156263 -1.19857883  1.38847184 -0.98953653
   -0.78299981  2.18921726  1.54421916  1.5305066  -1.28086073
    2.31988343 -0.50405456 -0.514213    1.00762079  0.30351509
   -1.06769039  0.27000234 -1.59531063 -1.10439876  0.275032
   -0.05950485 -0.43121099 -0.67757309 -0.29537562 -0.85793679
   -0.28913992 -1.16336595  0.31835729  0.55263161 -0.21645467
   -0.52667892  1.14673374 -0.00531444 -0.30647242  1.42481426
   -0.57809768  0.34900209  2.31437667 -0.01108027  0.21145963
   -0.91433977 -0.53363234  0.62250672 -1.10617814]]], shape=(1, 1, 64), dtype=float64)
